@startuml
'Author: Hayden Carpenter
'Last Edit: 2023-01-03
title Back to Login
header Last edit: 2023-01-03
actor User
participant BattleShipApp as gui
gui->User:Displays End of Game screen
User->gui:Clicks 'Back to Menu' button
gui->User:Logs out both users and returns to login screen