@startuml
'Author: Hayden Carpenter
'Last Edit: 2023-01-03
title Quit Application
header Last edit: 2023-01-03
actor User
participant BattleShipApp as gui
gui->User:Displays End of Game screen
User->gui:Clicks 'Quit Application' button
gui->User:Exits application